### ISSUE TITLE
Should this really be developed in its own repo and also be part of the Org-Mode repo?

### ISSUE THREAD

**Issue by tarsius** [larstvei/ox-gfm#14]
Why is `ox-gfm.el` developed in this repository but also tracked in the contrib directory of Org-Mode's repository. I think this is problematic because it means that at least for users who install the `org-plus-contrib` package from the Org-Mode Elpa as well as `ox-gfm` from Melpa it is undefined which version will be used (depends on the order of `load-path`).

So I would recommend that you either remove `ox-gfm.el` from Org-Mode's contrib directory or remove `ox-gfm` from Melpa.  If you choose to do the latter, then you might even want to consider to remove this repository and develop directly in the Org-Mode repository instead.

/cc @purcell

**Comment by larstvei** [comment]
This was raised in #5.

I never submitted this package to melpa, someone else did (which I can't stop them from doing). I don't consider this as an issue, and so I'm not going to make an effort to get it removed. I like that the package is available through melpa, as I think it reaches more users, but if the maintainers of melpa think it should be removed then that is fine by me.

**Comment by tarsius** [comment]
The problem is that the readme of this package sais (emphasize mine):

> The exporter has made it's way into to the contrib section of Org, and can be found here:
> http://orgmode.org/cgit.cgi/org-mode.git/plain/contrib/lisp/ox-gfm.el
> If changes are made, these will appear here **before they are suggested to the Org mode mailing list**.

Whille the history in the org repository looks like this:

```
commit f4ffbccf64470858e3d0ad77fa6ab65a0732898d
Author: Nicolas Goaziou <mail@nicolasgoaziou.fr>
Date:   Wed Jan 6 22:50:22 2016 +0100

    Remove left-over :export-block keywords
    
    * contrib/lisp/ox-freemind.el (freemind):
    * contrib/lisp/ox-gfm.el (gfm):
    * contrib/lisp/ox-groff.el (groff): Remove :export-block keyword.
    
    * doc/org.texi (Adding export back-ends): Remove documentation about the
      keyword.
    
    Reported-by: Kaushal Modi <kaushal.modi@gmail.com>
    <http://permalink.gmane.org/gmane.emacs.orgmode/104057>

commit b3987ed79e70f0749728835ccaaf296eac1d263c
Author: Bastien Guerry <bzg@altern.org>
Date:   Fri Apr 11 12:27:41 2014 +0200

    Add contrib/lisp/ox-gfm.el by Lars Tveito
```

I.e. you either have not tried to get your changes since 2014 merged into the version in Org-Mode or your changes were rejected (which seems unlikely since you are the original author). Do you intend to change this and start getting your changes into Org-Mode? If not, then I think the best course of action would be to remove the old version from Org-Mode.

**Comment by bzg** [comment]
Hi all,

I agree the best move is to remove `ox-gfm.el` from the "contrib/" directory.

@larstvei if you're okay with this, I will remove ox-gfm.el from the master branch.

Thanks @tarsius for the ping!

PS: I'm all for moving everything out of the "contrib/" directory, which is useless nowadays.  But I would like to find a way to promote Org-related packages - perhaps something as simple as `(package-menu-filter '("org-mode" "ox"))`

**Comment by tarsius** [comment]
> I'm all for moving everything out of the "contrib/" directory, which is useless nowadays.

Nice to hear that!

**Comment by larstvei** [comment]
Go ahead and remove it from the master @bzg.

Thanks for the note on the README @tarsius, you are right, the changes should have made its way into org-mode, but I never got around to doing it; I'll remove the comment asap. When the file is removed from "contrib/" then all should be fine?

**Comment by tarsius** [comment]
Thanks @larstvei. Yes, then we are all good ;-)

**Comment by bzg** [comment]
I've just removed it from the master branch. Thanks!
