### ISSUE TITLE
Fix Icompatibility With New Org

### ISSUE THREAD

**Issue by cooperstevenson** [larstvei/ox-gfm#15]
This export block no longer works with the new Org mode structure and will flag an error on emacs' startup:

./elpa/ox-gfm-20160520.2040/ox-gfm.el
  :export-block '("GFM" "GITHUB FLAVORED MARKDOWN")

I found that commenting out the :export-block line no longer generates a startup error.

**Comment by larstvei** [comment]
Hi, thanks for reporting!

Is it long since you have updated `ox-gfm`? This should have been fixed in 4377711.

**Comment by larstvei** [comment]
Since you haven't answered this, and I strongly suspect that the problem was fixed in 4377711, I'll close the issue. Please reopen if there still is a problem.
