### ISSUE TITLE
ox-gfm removes `mailto:` prefix from email links

### ISSUE THREAD

**Issue by thriveth** [larstvei/ox-gfm#17]
When I have links of the type

    [[mailto:some.email@server.net][Jane Doe]]

it gets exported by ox-gfm as

    (Jane Doe)[some.email@server.net)

without the leading `mailto:`, resulting in a broken link when uploaded to e.g. GitHub.

**Comment by larstvei** [comment]
Hi! Thanks for raising the isssue.

`ox-gfm.el` is derived from `ox-md.el`, which is a part of Org mode. This package tries to add features that are specific for github flavored markdown. Links behave the same way in both github flavored and traditional markdown; fixing it in `ox-md.el` would fix it for `ox-gfm.el` killing two birds with one stone.

Could you perhaps raise the issue on the Org mailing list?

**Comment by jgkamat** [comment]
I've created a patch to try and fix this, and posted it to the org mailing list. The message is here: http://lists.gnu.org/archive/html/emacs-orgmode/2017-07/msg00206.html. Hopefully it will get merged into upstream, but you can apply the (tiny) patch now if it's critical for some reason.

**Comment by jgkamat** [comment]
This is upstream now, and hopefully will be a part of the next org release! :)

**Comment by larstvei** [comment]
Fantastic! Thanks for your contribution :)
