### ISSUE TITLE
Couldn't export (Wrong number of arguments)

### ISSUE THREAD

**Issue by oystersauce8** [larstvei/ox-gfm#25]
When exporting I get

Wrong number of arguments: #[(data info) "Ã\211^X^YÄ\211^YÅ
Æ\"!\210Ç^H!+\207" [num-alist collect-fn info nil #[(data) "Â^HÃÄ       ÅÆ&^F\207" [data info org-element-map fo\
otnote-reference #[(fn) "Æ^H    \"\205O^@Ç^H    \"^ZÈ^H \"É^H^[^\^K;\203!^@ÊË^L^K#\202'^@Ì^KA@^L\"*
E^MB^UÍ^H^[^\^K;\203>^@ÊË^L^K#\202D^@Ì^KA@^L\"*Î=\205N^@^N^O
!)\207" [fn info def element property num-alist org-export-footnote-first-reference-p org-export-get-footnote-de\
finition org-export-get-footnote-number :label ...] 5] nil footnote-definition] 7] plist-get :parse-tree reverse\
] 5 ("/usr/local/Cellar/emacs/25.3/share/emacs/25.3/lisp/org/ox.elc" . 110393)], 1

**Comment by larstvei** [comment]
Ok, not much to go on here. Some questions:

- Do you get errors exporting to other formats? For instance HTML or regular markdown. If so, it's not this package.
- What is the source that you are trying to export?
- What version of org mode are you using?
- Are you running the lasted version of this package?

**Comment by larstvei** [comment]
I'm closing this, as there is no way for me to debug this with the provided information. Feel free to reopen this if you can provide steps to reproduce the issue.
