### ISSUE TITLE
TODO Keywords are not being exported

### ISSUE THREAD

**Issue by ganesh-krishnan** [larstvei/ox-gfm#26]
When I use ox-gfm, I find that my TODO keywords are not exporting with the doc. I've set the export option for TODO keywords to t and verified that the option is being set. 

Is this expected behavior?

**Comment by larstvei** [comment]
Hi, sorry for the late reply.

I'm going to give a similar answer to #17 and #21. This problem also occurs in the standard markdown exporter. Becuase ox-gfm is derived from that it would be preferable to fix the problem there, killing two birds with one stone.

Could you perhaps report the problem on the Org mailing list?

**Comment by ganesh-krishnan** [comment]
@larstvei Yup, I can do that. Thanks for the package! It's really useful.

**Comment by ganesh-krishnan** [comment]
@larstvei This is now fixed upstream.

**Comment by larstvei** [comment]
Wow, that was fast!

Thanks for getting this fixed!
