### ISSUE TITLE
Suggest add a tag

### ISSUE THREAD

**Issue by tumashu** [larstvei/ox-gfm#27]
Suggest add a tag, which is useful for melpa-stable and guixsd

**Comment by larstvei** [comment]
I don't fully understand the issue. Do you want me to create a release so the package is available in melpa-stable?

**Comment by tumashu** [comment]
yes， guixsd need a tarball to download， when create a tag,  a tarball is auto created.

**Comment by larstvei** [comment]
[This](https://github.com/larstvei/ox-gfm/releases/tag/v1.0) should resolve the problem.

Thanks for reporting!
