### ISSUE TITLE
Symbol's function definition is void: org-export-get-reference

### ISSUE THREAD

**Issue by Red-Portal** [larstvei/ox-gfm#28]
Calling ```org-gfm-export-as-markdown``` leads to that error.

I'm using emacs 25.3 and my org version is 8.2.10

**Comment by larstvei** [comment]
Hi, thanks for reporting!

Could you try to manually evaluate:

```
(require 'ox)
```

and try to export after?

**Comment by Red-Portal** [comment]
Too bad, still the same.

```lisp
(require 'ox)

(eval-after-load "org"
  (use-package ox-gfm
    :ensure t
    :config
    (setq org-src-fontify-natively t)))

```
Here's the relevant snippet.
with or without
```lisp
(require 'ox)
```

doesn't do much.
I also tried to eval (require 'ox) on ielm manually.
didn't help

**Comment by larstvei** [comment]
My guess is that something has gone wrong in your installation of Org mode (based on [this thread](https://lists.gnu.org/archive/html/emacs-orgmode/2015-08/msg00317.html)).

Try invoking `C-u M-x org-reload` which reloads org from source, and try exporting after. If this works, then try to recompile your org installation (or just delete and install (or even update!) from package-list-packages).

**Comment by Red-Portal** [comment]
Nope! That didn't do a lot

**Comment by larstvei** [comment]
Sorry for not realizing this sooner: `org-export-get-reference` was first introduced in version 8.3, so you need to upgrade your Org mode.

**Comment by Red-Portal** [comment]
It works well now thanks for the great package!

**Comment by LanternD** [comment]
I encountered the same issue today after I try to export .md through ox-gfm. 

> unknown "nil" back-end: Aborting export with no output

My previous Org version is 8.2.x. Now I upgrade to Org 9.1.2 and then I can export the markdown file as my expectation now. Thanks! Great package.

**Comment by Ynjxsjmh** [comment]
I also run into this issue even after I restart my emacs. My Org version is 9.1.9.

But after I execute `C-u M-x org-reload` mentioned above, it works out after that.

Thanks for the great package!
