### ISSUE TITLE
Variables to disable TOC

### ISSUE THREAD

**Issue by waltervargas** [larstvei/ox-gfm#29]
Hi, 

Thank you for developing this exporter, it's possible to have the a variable to enable/disable TOC?

Thank you.

**Comment by larstvei** [comment]
Yes. It's a org-mode feature that is supported by ox-gfm, and is documented in the [org mode manual](http://orgmode.org/manual/Table-of-contents.html),

The following org file would produce a markdown file with a table of contents:

```org
#+TITLE: TEST
#+OPTIONS: toc:t
* Headline 1
```

This one would not include a table of contents:

```org
#+TITLE: TEST
#+OPTIONS: toc:nil
* Headline 1
```

**Comment by waltervargas** [comment]
Hey @larstvei thank you for your answer!
