### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by Distopico** [larstvei/ox-gfm#3]
Hi, thanks for your code, is very useful, I have a question... you think implement support for tables?

https://help.github.com/articles/github-flavored-markdown/#tables

thanks for you time...

**Comment by larstvei** [comment]
Hi!

I haven't had much time to work on this, but it's definitely the first thing I'll get to when I get the time.

If someone find the time to implement this, please submit a pull request!

- Lars

**Comment by Distopico** [comment]
ok thanks.. ;)

**Comment by larstvei** [comment]
I completely forgot about this, but received a pull request a while ago. This should be fixed now. See #6.

**Comment by Distopico** [comment]
thanks
