### ISSUE TITLE
cannot use package

### ISSUE THREAD

**Issue by Krisselack** [larstvei/ox-gfm#36]
I seem to have troubles using the extension. It doesn`t show up in the export dispatcher. 
When I run it manually (M-x org-gfm-export-to-markdown) I get the following error: 
Unknown "nil" back-end: Aborting export 

Emacs version (Ubuntu 18.04): 
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)
 of 2017-09-22, modified by Debian 
Package versions: 
org 9.1.14 
ox-gfm: 20170628.2102

.emacs.d:
`(require 'ox)

(eval-after-load "org"
  (use-package ox-gfm
    :ensure t
    :config
    (setq org-src-fontify-natively t)))
`

**Comment by rileyrg** [comment]
I'm getting the same issue today. 

Unknown "nil" back-end: Aborting export

running org-gfm-export-to-markdown from an org-mode buffer

init code direct form the docs:-
```

(eval-after-load "org"
  '(require 'ox-gfm nil t))  

```

**Comment by rileyrg** [comment]
update:- a previous answer works (documented install code doesnt)
```

(use-package ox-gfm
  :defer 3
  :after org)
```

**Comment by larstvei** [comment]
Hi!

If you evaluate

```
(eval-after-load "org"
  '(require 'ox-gfm nil))
```

without the `t` argument. Do you get an error? I'm not able to reproduce the error.

**Comment by rileyrg** [comment]
no error at that point, but later the nil backend error when I tried to export. Sorry, I dont have the exact details. I can come back in a day or two and reproduce but it works now so I'm happy,
