### ISSUE TITLE
Installing ox-gfm from MELPA seems to be problematic

### ISSUE THREAD

**Issue by syl20bnr** [larstvei/ox-gfm#4]
When I install `ox-gfm` from MELPA some org functions become undefined.
If I remove the file `org-loaddefs.el` from the install directory of `ox-gfm` then everything works fine. Is it possible that this file shadows the original feature `org-loaddefs` ?

**Comment by larstvei** [comment]
Hi!

I never submitted this package to MELPA, so I'm not really sure about this. I saw you've asked over at MELPA, hope you find better answers there.

**Comment by syl20bnr** [comment]
Thank you, I suppose you have no idea about the `orf-loaddefs.el` file ?

**Comment by larstvei** [comment]
Sorry, I don't. I've read the MELPA-recipie and I don't see why it would download any files besides `ox-gfm.el`.

**Comment by syl20bnr** [comment]
Seems it is generated along with the auotloads.
Thank you!

**Comment by conklech** [comment]
The file-local variable `generated-autoload-file` is set to `"org-loaddefs.el"` in [ox-gfx.el](https://github.com/larstvei/ox-gfm/blob/master/ox-gfm.el#L187) in this repository. I'm not familiar with emacs; perhaps that causes the autoload and should be changed?

**Comment by purcell** [comment]
Yes, `generated-autoload-file` should not be overridden like this. It will cause any other `org-loaddefs.el` in `load-path` to be shadowed, and prevent the autoloads from having any effect when installed as a package.

**Comment by larstvei** [comment]
I see, fixed it now, thanks!
